name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Launch EC2 instance
        id: launch-ec2
        run: |
          instance_id=$(aws ec2 run-instances \
            --image-id ami-0123456789abcdef0 \
            --instance-type t2.micro \
            --security-group-ids sg-0123456789abcdef0 \
            --subnet-id subnet-0123456789abcdef0 \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "Instance ID: $instance_id"
          echo "INSTANCE_ID=$instance_id" >> $GITHUB_ENV

      - name: Wait for EC2 instance to start
        run: |
          aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }}

      - name: Retrieve instance public IP
        id: get-instance-ip
        run: |
          instance_public_ip=$(aws ec2 describe-instances \
            --instance-ids ${{ env.INSTANCE_ID }} \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
          echo "Instance Public IP: $instance_public_ip"
          echo "INSTANCE_PUBLIC_IP=$instance_public_ip" >> $GITHUB_ENV

      - name: Install and configure httpd
        run: |
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/known_hosts
          ssh-keyscan -H ${{ env.INSTANCE_PUBLIC_IP }} >> $HOME/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh -i $HOME/.ssh/id_rsa ec2-user@${{ env.INSTANCE_PUBLIC_IP }} 'sudo yum install -y httpd'
          # Copy your website's files to /var/www/html
          # Configure httpd and start the service

      - name: Deploy to EC2 instance
        run: |
          scp -i $HOME/.ssh/id_rsa -r <path-to-website-files> ec2-user@${{ env.INSTANCE_PUBLIC_IP }}:/var/www/html/

      - name: Test website
        run: |
          # Perform any necessary tests on the deployed website

      - name: Clean up
        run: |
          aws ec2 terminate-instances --instance-ids ${{ env.INSTANCE_ID }}
