name: Deploy EC2 Instance and Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Launch EC2 instance
      id: launch-ec2
      run: |
        instance_id=$(aws ec2 run-instances \
          --image-id ami-022e1a32d3f742bd8 \
          --instance-type t2.micro \
          --security-group-ids sg-0ef2a0a9a7dc4c932 \
          --subnet-id subnet-05669903535280275 \
          --query 'Instances[0].InstanceId' \
          --output text)
        echo "Instance ID: $instance_id"
        echo "INSTANCE_ID=$instance_id" >> $GITHUB_ENV

        aws ec2 wait instance-running --instance-ids $instance_id

    - name: Retrieve instance public IP
      id: get-instance-ip
      run: |
        instance_public_ip=$(aws ec2 describe-instances \
          --instance-ids ${{ env.INSTANCE_ID }} \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)
        echo "Instance Public IP: $instance_public_ip"
        echo "INSTANCE_PUBLIC_IP=$instance_public_ip" >> $GITHUB_ENV

    - name: Create .ssh directory
      run: |
        mkdir -p $HOME/.ssh

    - name: Add EC2 instance to known hosts
      run: |
        ssh-keyscan -H ${{ env.INSTANCE_PUBLIC_IP }} >> $HOME/.ssh/known_hosts

    - name: SSH into EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa ec2-user@${{ env.INSTANCE_PUBLIC_IP }} exit

    - name: Install Apache HTTP Server
      run: |
        ssh -i $HOME/.ssh/id_rsa ec2-user@${{ env.INSTANCE_PUBLIC_IP }} 'sudo yum install -y httpd'

    - name: Copy website files to EC2 instance
      run: |
        git clone https://github.com/bibin567/project.git
        scp -i $HOME/.ssh/id_rsa -r project ec2-user@${{ env.INSTANCE_PUBLIC_IP }}:/var/www/html/

    - name: Start Apache HTTP Server
      run: |
        ssh -i $HOME/.ssh/id_rsa ec2-user@${{ env.INSTANCE_PUBLIC_IP }} 'sudo systemctl start httpd'

    - name: Print Website URL
      run: |
        echo "Website URL: http://${{ env.INSTANCE_PUBLIC_IP }}"

